#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > tmp.txt
sudo cp tmp.txt /var/www/html/index.html
rm tmp.txt
sudo service nginx start
